%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    C:\Users\takanori\Documents\MATLAB\multiRegr\data_local\csv\MDF_NKIRS_ICA.csv
%    Worksheet: MDF_NKIRS_ICA
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/06/10 18:26:43
clear
%% Import the data
[~, ~, raw1] = xlsread('C:\Users\takanori\Documents\MATLAB\multiRegr\data_local\csv\MDF_NKIRS_ICA.csv','MDF_NKIRS_ICA','A1:A330');
[~, ~, raw2] = xlsread('C:\Users\takanori\Documents\MATLAB\multiRegr\data_local\csv\MDF_NKIRS_ICA.csv','MDF_NKIRS_ICA','AJ1:AJ330');

SubjList=raw1(2:end)


exclusionCriteriaName = raw2{1}
mask = cell2mat(raw2(2:end))
%%